[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r public .next/standalone/public || true",
  "cp -r .next/static .next/standalone/.next/static || true"
]

[start]
cmd = "node .next/standalone/server.js"
