"use client";

import { useState } from "react";
import {
  FileText,
  CheckSquare,
  Zap,
  AlertTriangle,
  Search,
  Calendar,
  Shield,
  MessageSquare,
  Copy,
  Download,
  ChevronDown,
  ChevronUp,
  GitGraph,
} from "lucide-react";
import { toast } from "sonner";
import { FormattedContent } from "./SectionCard";
import { RedFlagsPanel } from "./RedFlagsPanel";
import { TimelinePanel } from "./TimelinePanel";
import { ConfidencePanel } from "./ConfidencePanel";
import { DiagramPanel } from "./DiagramPanel";
import { QAPanel } from "./QAPanel";
import { cn } from "@/lib/utils/cn";
import { parseJsonSection } from "@/lib/utils/parseSections";
import type {
  ParsedSections,
  AnalysisStatus,
  Layer1Result,
  Layer3Result,
  RedFlag,
  KeyDate,
} from "@/types";

interface ResultDocumentProps {
  sections: ParsedSections;
  status: AnalysisStatus;
  layer1Result: Layer1Result | null;
  layer3Result: Layer3Result | null;
  contractText: string;
  privacyMode?: boolean;
}

const isStreaming = (status: AnalysisStatus) =>
  status === "streaming" || status === "verifying";

// ── Inline section loading indicator ────────────────────────────────────────
function SectionLoader() {
  return (
    <div className="flex items-center gap-2 py-3 text-sm text-muted-foreground">
      <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse shrink-0" />
      Generating…
    </div>
  );
}

// ── Section wrapper: titled card ─────────────────────────────────────────────
function DocSection({
  icon: Icon,
  title,
  iconColor = "text-muted-foreground",
  badge,
  children,
  className,
}: {
  icon: React.ElementType;
  title: string;
  iconColor?: string;
  badge?: React.ReactNode;
  children: React.ReactNode;
  className?: string;
}) {
  return (
    <div className={cn("rounded-xl border border-border overflow-hidden", className)}>
      <div className="flex items-center gap-2 bg-muted/40 border-b border-border px-4 py-2.5">
        <Icon className={cn("h-3.5 w-3.5 shrink-0", iconColor)} />
        <span className="text-xs font-semibold uppercase tracking-wide text-foreground">
          {title}
        </span>
        {badge}
      </div>
      <div className="bg-card px-4 py-4">{children}</div>
    </div>
  );
}

// ── Build plain-text export ──────────────────────────────────────────────────
function buildPlainText(
  layer1Result: Layer1Result | null,
  sections: ParsedSections
): string {
  const lines: string[] = [];

  lines.push("CONTRACT ANALYSIS REPORT");
  lines.push("========================");
  if (layer1Result) {
    lines.push(`Type: ${layer1Result.contractType}`);
    lines.push(`Jurisdiction: ${layer1Result.jurisdiction}`);
    lines.push(`You are: ${layer1Result.signerRole}`);
    lines.push(`Other party: ${layer1Result.counterpartyRole}`);
  }
  lines.push("");

  const addSection = (title: string, content?: string) => {
    if (!content) return;
    lines.push(`\n${title.toUpperCase()}`);
    lines.push("-".repeat(title.length));
    lines.push(content);
  };

  addSection("Summary", sections.SUMMARY);
  addSection("Your Obligations", sections.OBLIGATIONS);
  addSection("Their Powers", sections.POWERS);
  addSection("Missing Clauses", sections.MISSING);

  if (sections.REDFLAGS) {
    try {
      const flags = JSON.parse(sections.REDFLAGS) as RedFlag[];
      if (flags.length > 0) {
        lines.push("\nRED FLAGS");
        lines.push("---------");
        flags.forEach((f, i) => {
          lines.push(`${i + 1}. [${f.severity}] ${f.clauseRef}`);
          lines.push(`   ${f.explanation}`);
          lines.push(`   Tip: ${f.negotiationTip}`);
        });
      }
    } catch { /* skip */ }
  }

  if (sections.TIMELINE) {
    try {
      const dates = JSON.parse(sections.TIMELINE) as KeyDate[];
      if (dates.length > 0) {
        lines.push("\nKEY DATES");
        lines.push("---------");
        dates.forEach((d) => {
          lines.push(`• ${d.label}: ${d.value}`);
        });
      }
    } catch { /* skip */ }
  }

  addSection("Confidence", sections.CONFIDENCE);

  lines.push("\n---");
  lines.push("Generated by PlainContracts — not legal advice.");
  return lines.join("\n");
}

// ── Main component ───────────────────────────────────────────────────────────
export function ResultDocument({
  sections,
  status,
  layer1Result,
  layer3Result,
  contractText,
  privacyMode,
}: ResultDocumentProps) {
  const [showQA, setShowQA] = useState(false);
  const [showConfidence, setShowConfidence] = useState(false);
  const streaming = isStreaming(status);
  const isDone = status === "done";

  const flags = parseJsonSection<RedFlag[]>(sections.REDFLAGS, []);
  const highCount = flags.filter((f) => f.severity === "High").length;

  const confidenceScore = (() => {
    if (!sections.CONFIDENCE) return null;
    const trimmed = sections.CONFIDENCE.trim();
    // Number at start
    const m = trimmed.match(/^(\d{1,3})[.):\s]/);
    if (m) { const s = parseInt(m[1], 10); if (s <= 100) return s; }
    // Bare number
    if (/^\d+$/.test(trimmed)) return Math.min(100, parseInt(trimmed, 10));
    // Number within first 60 chars (non-English prefixes like "Score : 52")
    const loose = trimmed.slice(0, 60).match(/\b(\d{1,3})\b/);
    if (loose) { const s = parseInt(loose[1], 10); if (s <= 100) return s; }
    return null;
  })();

  const handleCopy = async () => {
    const text = buildPlainText(layer1Result, sections);
    await navigator.clipboard.writeText(text);
    toast.success("Report copied to clipboard");
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div id="report-document" className="space-y-4">
      {/* ── Action bar ────────────────────────────────────────────── */}
      <div className="rounded-xl border border-border bg-card px-4 py-3 flex flex-col sm:flex-row sm:items-center gap-3 print:hidden">
        {/* Contract meta */}
        <div className="flex-1 min-w-0 flex flex-wrap items-center gap-2 text-sm">
          {layer1Result ? (
            <>
              <span className="font-semibold text-foreground capitalize">
                {layer1Result.contractType.replace(/[_-]/g, " ")}
              </span>
              {layer1Result.jurisdiction !== "Not stated" && (
                <span className="text-muted-foreground text-xs">
                  · {layer1Result.jurisdiction}
                </span>
              )}
              {highCount > 0 && (
                <span className="inline-flex items-center gap-1 bg-red-100 dark:bg-red-950/40 text-red-700 dark:text-red-400 text-xs font-medium px-2 py-0.5 rounded-full">
                  <AlertTriangle className="h-3 w-3" />
                  {highCount} high-risk {highCount === 1 ? "clause" : "clauses"}
                </span>
              )}
              {confidenceScore !== null && (
                <span
                  className={cn(
                    "text-xs font-medium px-2 py-0.5 rounded-full",
                    confidenceScore >= 70
                      ? "bg-green-100 dark:bg-green-950/40 text-green-700 dark:text-green-400"
                      : "bg-amber-100 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400"
                  )}
                >
                  {confidenceScore}% confidence
                </span>
              )}
            </>
          ) : (
            <div className="h-4 w-48 rounded bg-muted animate-pulse" />
          )}
        </div>

        {/* Export buttons — only once done */}
        {isDone && (
          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground border border-border rounded-md px-3 py-1.5 hover:bg-accent transition-colors"
            >
              <Copy className="h-3.5 w-3.5" />
              Copy report
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground border border-border rounded-md px-3 py-1.5 hover:bg-accent transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              Export PDF
            </button>
          </div>
        )}
      </div>

      {/* ── Print-only header ─────────────────────────────────────── */}
      <div className="hidden print:block mb-4">
        <h1 className="text-2xl font-bold">Contract Analysis Report</h1>
        {layer1Result && (
          <p className="text-sm text-gray-600 mt-1">
            {layer1Result.contractType} &middot; {layer1Result.jurisdiction} &middot;{" "}
            {layer1Result.signerRole} ↔ {layer1Result.counterpartyRole}
          </p>
        )}
        <p className="text-xs text-gray-400 mt-1">
          PlainContracts &mdash; translation tool only, not legal advice
        </p>
        <hr className="mt-3 border-gray-200" />
      </div>

      {/* ── Visual Overview ───────────────────────────────────────── */}
      <DocSection icon={GitGraph} title="Visual Overview">
        <DiagramPanel
          layer1Result={layer1Result}
          sections={sections}
          status={status}
        />
      </DocSection>

      {/* ── Plain Summary ─────────────────────────────────────────── */}
      <DocSection icon={FileText} title="Plain Summary">
        {sections.SUMMARY ? (
          <FormattedContent text={sections.SUMMARY} />
        ) : (
          <SectionLoader />
        )}
      </DocSection>

      {/* ── Obligations + Their Powers ────────────────────────────── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <DocSection
          icon={CheckSquare}
          title="Your Obligations"
          iconColor="text-primary"
        >
          {sections.OBLIGATIONS ? (
            <FormattedContent text={sections.OBLIGATIONS} />
          ) : streaming ? (
            <SectionLoader />
          ) : (
            <p className="text-sm text-muted-foreground">
              No obligations identified.
            </p>
          )}
        </DocSection>

        <DocSection icon={Zap} title="Their Powers" iconColor="text-amber-500">
          {sections.POWERS ? (
            <FormattedContent text={sections.POWERS} />
          ) : streaming ? (
            <SectionLoader />
          ) : (
            <p className="text-sm text-muted-foreground">
              No special powers identified.
            </p>
          )}
        </DocSection>
      </div>

      {/* ── Red Flags ─────────────────────────────────────────────── */}
      <DocSection
        icon={AlertTriangle}
        title="Red Flags"
        iconColor="text-red-500"
        badge={
          flags.length > 0 ? (
            <span className="ml-1 bg-red-500 text-white rounded-full px-1.5 py-0.5 text-xs leading-none font-medium">
              {flags.length}
            </span>
          ) : undefined
        }
      >
        {sections.REDFLAGS ? (
          <RedFlagsPanel content={sections.REDFLAGS} streaming={streaming} />
        ) : streaming ? (
          <SectionLoader />
        ) : (
          <p className="text-sm text-muted-foreground">
            No red flags identified.
          </p>
        )}
      </DocSection>

      {/* ── Missing Clauses + Key Dates ──────────────────────────── */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <DocSection
          icon={Search}
          title="Missing Clauses"
          iconColor="text-orange-500"
        >
          {sections.MISSING ? (
            <FormattedContent text={sections.MISSING} />
          ) : streaming ? (
            <SectionLoader />
          ) : (
            <p className="text-sm text-muted-foreground">
              No missing clauses identified.
            </p>
          )}
        </DocSection>

        <DocSection icon={Calendar} title="Key Dates" iconColor="text-blue-500">
          {sections.TIMELINE ? (
            <TimelinePanel content={sections.TIMELINE} streaming={streaming} />
          ) : streaming ? (
            <SectionLoader />
          ) : (
            <p className="text-sm text-muted-foreground">No key dates found.</p>
          )}
        </DocSection>
      </div>

      {/* ── Confidence & Details (collapsible) ───────────────────── */}
      <div className="rounded-xl border border-border overflow-hidden print:block">
        {/* Toggle button — hidden in print */}
        <button
          onClick={() => setShowConfidence(!showConfidence)}
          className="w-full flex items-center justify-between gap-2 bg-muted/40 border-b border-border px-4 py-2.5 hover:bg-muted/60 transition-colors print:hidden"
        >
          <div className="flex items-center gap-2">
            <Shield className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
            <span className="text-xs font-semibold uppercase tracking-wide text-foreground">
              Confidence &amp; Analysis Details
            </span>
            {confidenceScore !== null && (
              <span
                className={cn(
                  "text-xs font-semibold",
                  confidenceScore >= 70
                    ? "text-green-600 dark:text-green-400"
                    : "text-amber-600 dark:text-amber-400"
                )}
              >
                {confidenceScore}/100
              </span>
            )}
          </div>
          {showConfidence ? (
            <ChevronUp className="h-3.5 w-3.5 text-muted-foreground" />
          ) : (
            <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
          )}
        </button>

        {/* Print header */}
        <div className="hidden print:flex items-center gap-2 bg-muted/40 border-b border-border px-4 py-2.5">
          <Shield className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
          <span className="text-xs font-semibold uppercase tracking-wide text-foreground">
            Confidence &amp; Analysis Details
          </span>
        </div>

        {/* Content — visible when expanded or in print */}
        {(showConfidence || !isDone) && (
          <div className="bg-card px-4 py-4 section-fade-in print:block">
            <ConfidencePanel
              content={sections.CONFIDENCE}
              layer1Result={layer1Result}
              layer3Result={layer3Result}
              streaming={streaming}
            />
          </div>
        )}
        <div className="hidden print:block bg-card px-4 py-4">
          <ConfidencePanel
            content={sections.CONFIDENCE}
            layer1Result={layer1Result}
            layer3Result={layer3Result}
            streaming={streaming}
          />
        </div>
      </div>

      {/* ── Ask a Question (collapsible, hidden in print) ─────────── */}
      <div className="rounded-xl border border-border overflow-hidden print:hidden">
        <button
          onClick={() => setShowQA(!showQA)}
          className="w-full flex items-center justify-between gap-2 bg-muted/40 border-b border-border px-4 py-2.5 hover:bg-muted/60 transition-colors"
        >
          <div className="flex items-center gap-2">
            <MessageSquare className="h-3.5 w-3.5 text-muted-foreground shrink-0" />
            <span className="text-xs font-semibold uppercase tracking-wide text-foreground">
              Ask a Question
            </span>
            <span className="text-xs text-muted-foreground normal-case font-normal tracking-normal">
              — follow-up anything about this contract
            </span>
          </div>
          {showQA ? (
            <ChevronUp className="h-3.5 w-3.5 text-muted-foreground" />
          ) : (
            <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />
          )}
        </button>
        {showQA && (
          <div className="bg-card px-4 py-4 section-fade-in">
            <QAPanel
              contractText={contractText}
              sections={sections}
              layer1Result={layer1Result}
              privacyMode={privacyMode}
            />
          </div>
        )}
      </div>
    </div>
  );
}
